wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epoch:
  desc: null
  value: 100
batch:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687759584.254168
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
